/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import view.Banhang.JpBanhang;
import view.Datban.JpDatban;
import view.Home.JpHome;
import view.QuanLy.JpQuanly;
import view.Thietlap.JpThietLap;
import view.Thongke.JpThongKe;

/**
 *
 * @author Admin
 */
public class frmain extends javax.swing.JFrame{

    JpHome home;

    /**
     * Creates new form Frmain
     */
    public frmain() {
        initComponents();
        fill();
    }

    public void fill() {
        home = new JpHome();
        jpLayout.add(home);
        jpLayout.updateUI();
        
  
            
          txtTen.setText(run.tk.getUsername());
          if (run.tk.getLever() !=1) {
            jquanly.setVisible(false);
            jthongke.setVisible(false);
            jthietlap.setVisible(false);
        }
        
        

     

    }
    JpBanhang banhang;
    JpDatban datban;
    JpQuanly ql;
    JpThongKe tk;
    JpThietLap tl;

    public void reloadPanel(int i) {
        jpLayout.removeAll();
        switch (i) {
            case 1:
                if (banhang == null) {
                    banhang = new JpBanhang();
                }
                setColor(jbanhang);
                resetColor(Jhome);
                resetColor(jdatban);
                resetColor(jthietlap);
                resetColor(jquanly);
                resetColor(jthongke);

                jpLayout.add(banhang);
                break;
            case 2:
                if (home == null) {
                    home = new JpHome();
                }
                resetColor(jbanhang);
                setColor(Jhome);
                resetColor(jdatban);
                resetColor(jthietlap);
                resetColor(jquanly);
                resetColor(jthongke);

                jpLayout.add(home);
                break;
            case 3:
                if (ql == null) {
                    ql = new JpQuanly();
                }
                resetColor(jbanhang);
                resetColor(Jhome);
                resetColor(jdatban);
                resetColor(jthietlap);
                setColor(jquanly);
                resetColor(jthongke);
                jpLayout.add(ql);

                break;
            case 4:
                tk = new JpThongKe();

                resetColor(jbanhang);
                resetColor(Jhome);
                resetColor(jdatban);
                resetColor(jthietlap);
                resetColor(jquanly);
                setColor(jthongke);
                jpLayout.add(tk);

                break;
            case 5:
                if (datban == null) {
                    datban = new JpDatban();
                }
                resetColor(jbanhang);
                resetColor(Jhome);
                setColor(jdatban);
                resetColor(jthietlap);
                resetColor(jquanly);
                resetColor(jthongke);

                jpLayout.add(datban);
                break;
            case 6:
                if (tl == null) {
                    tl = new JpThietLap();
                }

                resetColor(jbanhang);
                resetColor(Jhome);
                resetColor(jdatban);
                setColor(jthietlap);
                resetColor(jquanly);
                resetColor(jthongke);
                jpLayout.add(tl);
                break;
            default:
                break;
        }
        jpLayout.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidepane = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jquanly = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Jhome = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jbanhang = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jthongke = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jthietlap = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jdatban = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtTen = new javax.swing.JLabel();
        jpLayout = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 77, 230));
        kGradientPanel1.setkGradientFocus(800);
        kGradientPanel1.setkStartColor(new java.awt.Color(238, 12, 110));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jquanly.setBackground(new java.awt.Color(153, 0, 153));
        jquanly.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jquanlyMousePressed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/quanly.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("QUẢN LÝ");

        javax.swing.GroupLayout jquanlyLayout = new javax.swing.GroupLayout(jquanly);
        jquanly.setLayout(jquanlyLayout);
        jquanlyLayout.setHorizontalGroup(
            jquanlyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jquanlyLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jquanlyLayout.setVerticalGroup(
            jquanlyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jquanlyLayout.createSequentialGroup()
                .addGroup(jquanlyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        kGradientPanel1.add(jquanly, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 250, 50));

        Jhome.setBackground(new java.awt.Color(153, 0, 153));
        Jhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JhomeMousePressed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("TRANG CHỦ");

        javax.swing.GroupLayout JhomeLayout = new javax.swing.GroupLayout(Jhome);
        Jhome.setLayout(JhomeLayout);
        JhomeLayout.setHorizontalGroup(
            JhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JhomeLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jLabel17)
                .addGap(111, 111, 111))
        );
        JhomeLayout.setVerticalGroup(
            JhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(jLabel17)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        kGradientPanel1.add(Jhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 250, 50));

        jbanhang.setBackground(new java.awt.Color(153, 0, 153));
        jbanhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbanhangMousePressed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/banhang.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("BÁN HÀNG");

        javax.swing.GroupLayout jbanhangLayout = new javax.swing.GroupLayout(jbanhang);
        jbanhang.setLayout(jbanhangLayout);
        jbanhangLayout.setHorizontalGroup(
            jbanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbanhangLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jbanhangLayout.setVerticalGroup(
            jbanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbanhangLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jbanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)))
        );

        kGradientPanel1.add(jbanhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 250, 50));

        jthongke.setBackground(new java.awt.Color(153, 0, 153));
        jthongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jthongkeMousePressed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/thongke.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("THỐNG KÊ");

        javax.swing.GroupLayout jthongkeLayout = new javax.swing.GroupLayout(jthongke);
        jthongke.setLayout(jthongkeLayout);
        jthongkeLayout.setHorizontalGroup(
            jthongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jthongkeLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jthongkeLayout.setVerticalGroup(
            jthongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jthongkeLayout.createSequentialGroup()
                .addGroup(jthongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        kGradientPanel1.add(jthongke, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 250, 50));

        jthietlap.setBackground(new java.awt.Color(153, 0, 153));
        jthietlap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jthietlapMousePressed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/thietlap.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("THIẾT LẬP");

        javax.swing.GroupLayout jthietlapLayout = new javax.swing.GroupLayout(jthietlap);
        jthietlap.setLayout(jthietlapLayout);
        jthietlapLayout.setHorizontalGroup(
            jthietlapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jthietlapLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jthietlapLayout.setVerticalGroup(
            jthietlapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jthietlapLayout.createSequentialGroup()
                .addGroup(jthietlapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jLabel14))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        kGradientPanel1.add(jthietlap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 250, 50));

        jdatban.setBackground(new java.awt.Color(153, 0, 153));
        jdatban.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jdatbanMousePressed(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/table.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("ĐẶT BÀN");

        javax.swing.GroupLayout jdatbanLayout = new javax.swing.GroupLayout(jdatban);
        jdatban.setLayout(jdatbanLayout);
        jdatbanLayout.setHorizontalGroup(
            jdatbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdatbanLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jdatbanLayout.setVerticalGroup(
            jdatbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdatbanLayout.createSequentialGroup()
                .addGroup(jdatbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jLabel16))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        kGradientPanel1.add(jdatban, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 250, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chuky.png"))); // NOI18N
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 70));
        kGradientPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 62, 250, 10));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chandung.png"))); // NOI18N
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, 110));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        jLabel8.setText("Đăng xuất");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });
        kGradientPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Xin chào:");
        kGradientPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 60, 22));

        txtTen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTen.setForeground(new java.awt.Color(0, 51, 51));
        txtTen.setText("aaaaa");
        kGradientPanel1.add(txtTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 150, 22));

        javax.swing.GroupLayout sidepaneLayout = new javax.swing.GroupLayout(sidepane);
        sidepane.setLayout(sidepaneLayout);
        sidepaneLayout.setHorizontalGroup(
            sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidepaneLayout.setVerticalGroup(
            sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );

        jpLayout.setBackground(new java.awt.Color(204, 204, 255));
        jpLayout.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidepane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpLayout, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidepane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JhomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JhomeMousePressed
        // TODO add your handling code here:
        reloadPanel(2);
    }//GEN-LAST:event_JhomeMousePressed

    private void jbanhangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbanhangMousePressed
        // TODO add your handling code here:
        reloadPanel(1);
    }//GEN-LAST:event_jbanhangMousePressed

    private void jdatbanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdatbanMousePressed
        // TODO add your handling code here:
        reloadPanel(5);
    }//GEN-LAST:event_jdatbanMousePressed

    private void jquanlyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jquanlyMousePressed
        // TODO add your handling code here:
        reloadPanel(3);
    }//GEN-LAST:event_jquanlyMousePressed

    private void jthongkeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jthongkeMousePressed
        // TODO add your handling code here:
        reloadPanel(4);
    }//GEN-LAST:event_jthongkeMousePressed

    private void jthietlapMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jthietlapMousePressed
        // TODO add your handling code here:
        reloadPanel(6);
    }//GEN-LAST:event_jthietlapMousePressed

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        // TODO add your handling code here:
        
 
             String ten = run.tk.getUsername();
       
        
        int kq = JOptionPane.showConfirmDialog(null, "Đăng xuất khỏi tài khoản " + ten + "?", "FBI Warning", JOptionPane.YES_NO_OPTION);
        if (kq ==JOptionPane.YES_OPTION) {
            run.login.thoat();
            txtTen.setText("");
            run.login.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jLabel8MousePressed

    void setColor(JPanel panel) {
        panel.setBackground(new Color(135, 112, 225));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(153, 0, 153));
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jhome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jbanhang;
    private javax.swing.JPanel jdatban;
    private javax.swing.JPanel jpLayout;
    private javax.swing.JPanel jquanly;
    private javax.swing.JPanel jthietlap;
    private javax.swing.JPanel jthongke;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JPanel sidepane;
    private javax.swing.JLabel txtTen;
    // End of variables declaration//GEN-END:variables
}
